import { SyntheticGene } from './types'

// Predefined synthetic genes library
export const syntheticGenes: SyntheticGene[] = [
  {
    id: 'gfp',
    name: 'GFP',
    description: 'Green Fluorescent Protein - widely used reporter gene',
    sequence: 'ATGGTGAGCAAGGGCGAGGAGCTGTTCACCGGGGTGGTGCCCATCCTGGTCGAGCTGGACGGCGACGTAAACGGCCACAAGTTCAGCGTGTCCGGCGAGGGCGAGGGCGATGCCACCTACGGCAAGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCCTGGCCCACCCTCGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA',
    category: 'fluorescent',
    tags: ['reporter', 'green', 'fluorescence']
  },
  {
    id: 'rfp',
    name: 'RFP',
    description: 'Red Fluorescent Protein - red reporter gene',
    sequence: 'ATGGTGAGCAAGGGCGAGGAGGATAACATGGCCATCATCAAGGAGTTCATGCGCTTCAAGGTGCACATGGAGGGCTCCGTGAACGGCCACGAGTTCGAGATCGAGGGCGAGGGCGAGGGCCGCCCCTACGAGGGCACCCAGACCGCCAAGCTGAAGGTGACCAAGGGTGGCCCCCTGCCCTTCGCCTGGGACATCCTGTCCCCTCAGTTCATGTACGGCTCCAAGGCCTACGTGAAGCACCCCGCCGACATCCCCGACTACTTGAAGCTGTCCTTCCCCGAGGGCTTCAAGTGGGAGCGCGTGATGAACTTCGAGGACGGAGGCGTGCTGACCCTGAAGTTCATCTGCACCACCGGCAAGCTGCCCGTGCCTCTGGCCGACCCTGGTGACCACCCTGACCTACGGCGTGCAGTGCTTCAGCCGCTACCCCGACCACATGAAGCAGCACGACTTCTTCAAGTCCGCCATGCCCGAAGGCTACGTCCAGGAGCGCACCATCTTCTTCAAGGACGACGGCAACTACAAGACCCGCGCCGAGGTGAAGTTCGAGGGCGACACCCTGGTGAACCGCATCGAGCTGAAGGGCATCGACTTCAAGGAGGACGGCAACATCCTGGGGCACAAGCTGGAGTACAACTACAACAGCCACAACGTCTATATCATGGCCGACAAGCAGAAGAACGGCATCAAGGTGAACTTCAAGATCCGCCACAACATCGAGGACGGCAGCGTGCAGCTCGCCGACCACTACCAGCAGAACACCCCCATCGGCGACGGCCCCGTGCTGCTGCCCGACAACCACTACCTGAGCACCCAGTCCGCCCTGAGCAAAGACCCCAACGAGAAGCGCGATCACATGGTCCTGCTGGAGTTCGTGACCGCCGCCGGGATCACTCTCGGCATGGACGAGCTGTACAAGTAA',
    category: 'fluorescent',
    tags: ['reporter', 'red', 'fluorescence']
  },
  {
    id: 'luciferase',
    name: 'Luciferase',
    description: 'Firefly luciferase - bioluminescent reporter',
    sequence: 'ATGGAAGACGCCAAAAACATAAAGAAAGGCCCGGCGCCATTCTATCCTCTAGAGGATGGAACCGCTGGAGAGCAACTGCATAAGGCTATGAAGAGATACGCCCTGGTTCCTGGAACAATTGCTTTTACAGATGCACATATCGAGGTGAACATCACGTACGCGGAATACTTCGAAATGTCCGTTCGGTTGGCAGAAGCTATGAAACGACATAAGGAAAACACTGTCGAGGCAGTTCCATAGGATGGCAAGATCCTGGTATTGGTCTGCGA',
    category: 'reporter',
    tags: ['bioluminescence', 'luciferase', 'reporter']
  }
]

// Helper function to get synthetic genes by category
export const getSyntheticGenesByCategory = (category: string): SyntheticGene[] => {
  return syntheticGenes.filter(gene => gene.category === category)
}

// Helper function to search synthetic genes
export const searchSyntheticGenes = (query: string): SyntheticGene[] => {
  const lowerQuery = query.toLowerCase()
  return syntheticGenes.filter(gene => 
    gene.name.toLowerCase().includes(lowerQuery) ||
    gene.description.toLowerCase().includes(lowerQuery) ||
    gene.tags.some(tag => tag.toLowerCase().includes(lowerQuery))
  )
} 